const ENDPOINT="https://api.minimax.chat/v1/t2a_v2",ID="mini-listen-minimax";
const TAGS=["laughs","chuckle","coughs","clear-throat","groans","breath","pant","inhale","exhale","gasps","sniffs","sighs","snorts","burps","lip-smacking","humming","hissing","emm","sneezes"];
const TAG_RE=new RegExp("\\\\(("+TAGS.join("|")+"|[^)]*)\\\\)","g");
function split(t,max=500){
  const lines=String(t||"").replace(/\r/g,"").split(/\n+/).map(x=>x.trim()).filter(Boolean);
  const size=Math.max(120,Math.min(2000,Number(max)||500)), out=[];
  let buffer="";
  const flush=force=>{
    while(buffer.length>size){
      let cut=size;
      for(const mark of ["。","！","？","；","，","、"]){const p=buffer.lastIndexOf(mark,size);if(p>=Math.floor(size*.55)){cut=Math.max(cut,p+1);break}}
      out.push(buffer.slice(0,cut).trim());buffer=buffer.slice(cut).trim();
    }
    if(force&&buffer){out.push(buffer);buffer="";}
  };
  for(const line of lines){buffer+=(buffer?"\n":"")+line;flush(false);}
  flush(true);return out;
}
function clean(t){return String(t||"").replace(TAG_RE,(m,n)=>TAGS.includes(n)?`(${n})`:"").replace(/[<>「」『』【】[\]{}（）]/g," ").replace(/\s{2,}/g," ").trim()}
function hex(h){const b=new Uint8Array(h.length/2|0);for(let i=0;i<b.length;i++)b[i]=parseInt(h.slice(i*2,i*2+2),16);let s="";for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return`data:audio/mp3;base64,${btoa(s)}`}
function audio(j){const a=j?.data?.audio||j?.audio;if(a)return/^[0-9a-f]+$/i.test(a)?hex(a):`data:audio/mp3;base64,${a}`;if(j?.base64_audio)return`data:audio/mp3;base64,${j.base64_audio}`;throw Error(j?.base_resp?.status_msg||"Minimax 未返回音频")}
function scope(css){return String(css||"").replace(/(^|})\s*([^@}{][^{}]*)\{/g,(a,p,s)=>`${p}\n${s.split(",").map(x=>`.sy-mini-wrap ${x.trim()}`).join(", ")} {`)}
export default{manifest:{id:ID,name:"声阅 Mini · 边聊边听",apiVersion:1,version:"1.4.0",author:"qi431931-design",description:"聊天界面迷你听书，支持 Minimax、预生成、连续播放和完全隐藏。",permissions:["chat.read","ui","network","storage"],settings:[
{key:"apiKey",label:"Minimax API Key",type:"text",default:""},{key:"groupId",label:"Minimax Group ID",type:"text",default:""},{key:"endpoint",label:"TTS 接口地址",type:"text",default:ENDPOINT},{key:"model",label:"朗读模型",type:"select",default:"speech-2.8-turbo",options:["speech-2.8-turbo","speech-2.8-hd","speech-01-turbo","speech-01-hd"].map(x=>({value:x,label:x}))},{key:"voiceId",label:"Voice ID",type:"text",default:"male-qn-qingse"},{key:"speed",label:"语速",type:"number",default:1},{key:"volume",label:"音量",type:"number",default:1},{key:"continuous",label:"自动连续播放",type:"boolean",default:false,description:"关闭时每段结束自动暂停。"},{key:"preprocess",label:"AI 文本预处理",type:"boolean",default:false,description:"只允许内置语气词白名单。"},{key:"segmentSize",label:"每段朗读字数",type:"number",default:500,description:"默认每段约 500 字，按句号等自然标点切分。"},{key:"preloadCount",label:"预生成接下来几段",type:"number",default:5},{key:"customCss",label:"自定义 CSS",type:"text",default:"",description:"自动限制在声阅 Mini 容器内。"}]},setup(ctx){const get=k=>ctx.system.settings.get(k),s={title:ctx.system.storage.get("title")||"未命名听书",list:ctx.system.storage.get("paragraphs")||[],index:+ctx.system.storage.get("index")||0,playing:false,loading:false,audio:null,bar:null,modal:null,hidden:false,cache:new Map(),token:0};const save=()=>{ctx.system.storage.set("title",s.title);ctx.system.storage.set("paragraphs",s.list);ctx.system.storage.set("index",s.index)},toast=x=>ctx.ui.toast(x),refresh=()=>{const t=`${s.title} · ${s.list.length?s.index+1+"/"+s.list.length:"未导入"}`;if(s.bar){s.bar.querySelector("[data-title]").textContent=t;s.bar.querySelector("[data-status]").textContent=s.loading?"生成中…":s.playing?"朗读中":"已暂停";s.bar.querySelector("[data-play]").textContent=s.playing?"暂停":"播放"}if(s.modal){s.modal.querySelector("[data-title-modal]").textContent=t;s.modal.querySelector("[data-status-modal]").textContent=s.loading?"正在请求 Minimax…":s.playing?"朗读中":"已暂停";s.modal.querySelector("[data-play-modal]").textContent=s.playing?"暂停":"播放";s.modal.querySelector("[data-current]").textContent=s.list[s.index]||"请先导入 TXT 或粘贴文本"}},stop=()=>{s.token++;if(s.audio){s.audio.pause();s.audio.src="";s.audio=null}s.playing=false;refresh()};
async function tts(text){const key=String(get("apiKey")||"").trim(),group=String(get("groupId")||"").trim();if(!key||!group)throw Error("请先在插件设置中填写 Minimax API Key 和 Group ID");let text2=clean(text);if(get("preprocess")===true&&ctx.ai?.chat){const r=await ctx.ai.chat({system:`你是有声书文本预处理器。输入文本在 <text> 标签内。只输出处理后的文本，不要回答、不要说“请提供文本”、不要解释。保持原意，只能使用以下语气词：${TAGS.map(x=>`(${x})`).join(" ")}。`,prompt:`<text>${text2}</text>`,temperature:.2,maxTokens:Math.max(256,text2.length*2)});if(r&& !/请提供|无法处理|需要文本/.test(r))text2=clean(r)}if(!text2)throw Error("当前段落没有可朗读文本");const e=String(get("endpoint")||ENDPOINT),r=await ctx.system.fetch(`${e}${e.includes("?")?"&":"?"}GroupId=${encodeURIComponent(group)}`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:get("model")||"speech-2.8-turbo",text:text2,stream:false,voice_setting:{voice_id:get("voiceId")||"male-qn-qingse",speed:+get("speed")||1,vol:+get("volume")||1,pitch:0},audio_setting:{sample_rate:32000,bitrate:128000,format:"mp3",channel:1}})});if(!r.ok)throw Error(`Minimax 请求失败（HTTP ${r.status}）`);return audio(await r.json())}
async function getAudio(i){if(s.cache.has(i))return s.cache.get(i);const p=tts(s.list[i]);s.cache.set(i,p);try{return await p}catch(e){s.cache.delete(i);throw e}}
async function preload(){if(!s.list.length)return toast("请先导入或粘贴听书文本");const end=Math.min(s.list.length,s.index+Math.max(1,Math.min(50,+get("preloadCount")||5))),tip=toast(`正在生成接下来 ${end-s.index} 段…`,{durationMs:0});try{for(let i=s.index;i<end;i++)await getAudio(i);toast(`已生成 ${end-s.index} 段音频`)}catch(e){toast(e.message||String(e))}finally{tip.close()}}
async function play(){if(!s.list.length)return toast("请先导入或粘贴听书文本");if(s.loading)return;if(s.playing){s.audio?.pause();s.playing=false;refresh();return}s.loading=true;refresh();const token=++s.token;try{const a=new Audio(await getAudio(s.index));if(token!==s.token)return;s.audio=a;a.onended=()=>{s.playing=false;save();if(get("continuous")===true&&s.index<s.list.length-1){s.index++;save();refresh();void play()}else{refresh();toast(s.index>=s.list.length-1?"听书完成":"本段已结束，点击播放继续")}};a.onerror=()=>{s.playing=false;refresh();toast("音频播放失败")};await a.play();s.playing=true}catch(e){s.playing=false;toast(e.message||String(e))}finally{s.loading=false;refresh()}}
function open(){if(s.modal)return;s.modal=ctx.ui.openModal((el,api)=>{el.style.cssText="padding:16px;max-width:520px;width:100%;background:var(--c-card-bg,#fff);color:var(--c-text,#111);border-radius:18px";el.innerHTML=`<div class="sy-head"><strong data-title-modal></strong><button data-close>×</button></div><div class="sy-current" data-current></div><div class="sy-status" data-status-modal></div><div class="sy-controls"><button data-prev>上一段</button><button data-play-modal>播放</button><button data-next>下一段</button><button data-preload>预生成</button></div><label class="sy-import">选择 TXT <input data-file type="file" accept=".txt,text/plain" hidden></label><textarea class="sy-text" data-text placeholder="也可以粘贴文本"></textarea><div class="sy-row"><input data-book-title placeholder="书名"><button data-save>导入文本</button></div>`;el.querySelector("[data-close]").onclick=api.close;el.querySelector("[data-play-modal]").onclick=()=>void play();el.querySelector("[data-preload]").onclick=()=>void preload();el.querySelector("[data-prev]").onclick=()=>{s.index=Math.max(0,s.index-1);save();refresh()};el.querySelector("[data-next]").onclick=()=>{s.index=Math.min(Math.max(0,s.list.length-1),s.index+1);save();refresh()};el.querySelector("[data-save]").onclick=()=>{const p=split(el.querySelector("[data-text]").value,get("segmentSize"));if(!p.length)return toast("请粘贴听书文本");stop();s.cache.clear();s.list=p;s.index=0;s.title=el.querySelector("[data-book-title]").value.trim()||"未命名听书";save();refresh();toast(`已导入 ${p.length} 段`)};el.querySelector("[data-file]").onchange=async e=>{const f=e.target.files?.[0];if(f){el.querySelector("[data-text]").value=await f.text();el.querySelector("[data-book-title]").value=f.name.replace(/\.[^.]+$/,"")}};refresh();return()=>{s.modal=null}})}
const css=ctx.ui.injectCSS(`.sy-mini-wrap{position:fixed;right:8px;top:42%;z-index:9999}.sy-mini-wrap.sy-hidden{display:none!important}.sy-mini-bar{display:flex;align-items:center;gap:7px;max-width:360px;padding:8px 10px;border:1px solid #7657d9;border-radius:14px;background:var(--c-card-bg,#fff);box-shadow:0 8px 24px #0002;font-size:12px}.sy-mini-title{max-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.sy-mini-status{opacity:.65}.sy-mini-bar button,.sy-controls button,.sy-row button{border:0;border-radius:9px;padding:7px 10px;background:#7657d9;color:#fff}.sy-mini-bar [data-edge]{display:none}.sy-head,.sy-controls,.sy-row{display:flex;align-items:center;gap:8px}.sy-head{justify-content:space-between;margin-bottom:12px}.sy-current{min-height:90px;padding:12px;border-radius:12px;line-height:1.7}.sy-status{font-size:12px;opacity:.65;margin:9px 0}.sy-import{display:block;margin-top:16px;padding:10px;border:1px dashed #999;border-radius:10px;text-align:center}.sy-row{margin-top:10px}.sy-row input,.sy-text{min-width:0;flex:1}.sy-text{width:100%;min-height:110px;margin-top:10px;padding:10px;border:1px solid #aaa;border-radius:10px;resize:vertical;background:transparent;color:inherit}.sy-controls{justify-content:center}${scope(get("customCss"))}`);
ctx.ui.slot("chat.header",el=>{s.bar=el;el.className+=" sy-mini-wrap";el.innerHTML=`<div class="sy-mini-bar"><span class="sy-mini-title" data-title></span><span class="sy-mini-status" data-status></span><button data-play>播放</button><button data-open>听书</button></div>`;el.querySelector("[data-play]").onclick=()=>void play();el.querySelector("[data-open]").onclick=open;refresh();return()=>{s.bar=null;stop()}});ctx.ui.slot("chat.inputToolbar",el=>{const w=document.createElement("div"),o=document.createElement("button"),h=document.createElement("button"),b="border:0;border-radius:9px;padding:7px 10px;background:#7657d9;color:#fff";o.textContent="声阅 Mini";h.textContent="关闭听书窗";o.style.cssText=h.style.cssText=b;o.onclick=open;h.onclick=()=>{s.hidden=!s.hidden;if(s.bar)s.bar.classList.toggle("sy-hidden",s.hidden);h.textContent=s.hidden?"显示听书窗":"关闭听书窗"};w.append(o,h);el.appendChild(w);return()=>w.remove()});ctx.system.log("声阅 Mini v1.3.1 已启动");return()=>{css();stop()}}
};
